### ISSUE TITLE
Improper project structure

### ISSUE THREAD

**Issue by abartoha** [FarhanaIslamSaima/Material_World_Server#1]
রিপজিটরির শুরুতে server ফোল্ডারের ভেতর কেন? রিপোজিটরি এক লেভেল উপিরে বসানো ভালো প্র্যাক্টিস না।

**Comment by FarhanaIslamSaima** [comment]
didn't know 'bout that. told you just a beginner .. 
ki korbo ekhn taile

**Comment by abartoha** [comment]
server ফোল্ডারের ভেতরের ফাইল গুলা কাট করে বাইরে আনো, তারপর add-commit-push

**Comment by FarhanaIslamSaima** [comment]
arekta folder open korbo ki? oitar mddhe server folder rakhbo?

**Comment by FarhanaIslamSaima** [comment]
accha wait

**Comment by FarhanaIslamSaima** [comment]
react er project o khulsi. eita teo ki problem? thakle let me know

**Comment by abartoha** [comment]
> react er project o khulsi. eita teo ki problem? thakle let me know

of course problem

one repo, one application.

ekhane just server er kaaj korbo. React front end er jonno arekta repo. Naile collaborative kaaj korte gele commit e commit e ekdm jogakhichuri howe jabe re.

**Comment by abartoha** [comment]
Rename the repo into "material_world_server"

Why?

In case I have to write this name into a terminal, it will be easier on my fingers. My fingers are struggling at 50 WPM.

**Comment by abartoha** [comment]
index.js koi -.-
